### ISSUE TITLE
Where to submit backyard football online crash/softlock reports?

### ISSUE THREAD

**Issue by benjmor** [scummvm/scummvm-sites#23]
(I am definitely submitting this issue in the wrong spot and apologize but would like help directing it to where it needs to go -- the original BYSO repos were archived and pointed to scummvm.)

The Backyard Football Online experience is more crash-prone than Backyard Baseball. 3 of my 4 games crashed, where the server stopped responding to input. Is there a way to gather any logs to try to resolve this issue?

**Comment by Thunderforge** [comment]
Thanks for being proactive and wanting to improve ScummVM by submitting crash/softlock reports!

The proper place to submit bug reports is https://bugs.scummvm.org. Be sure to include the version of ScummVM you are using (either 2.8.0 or the latest daily build) and info about your copy of Backyard Football (e.g. Windows version from the original CD).

Please refer to [the help docs](https://docs.scummvm.org/en/v2.8.0/help/report_bugs.html) for further information on how to report a bug and for info on how to find your log files.
